# Ejercicio 
import numpy as np
import matplotlib.pyplot as plt

def factorial(n):
    resultado = 1
    if n >= 1:
        for i in range(1, n+1):
            resultado *= i
    return resultado



print("*** Serie de Taylor para aproximar exp(x) ***")
terminos = int(input("Cuantos términos: "))
x = float(input("Valor de x: "))


aproximacion = 0

for tmp in range(0, terminos):
    
    aproximacion += (x**tmp) / factorial(tmp)
   
    print("x^" + str(tmp) + " / " + str(tmp) + "!")

print("Valor de aproximación: {:4.4}".format(aproximacion))
print("Valor real: {:4.4}".format( np.exp(x) ) )
